# Generated by Django 5.2.1 on 2025-12-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='last_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
